import Link from "next/link";
import { ArrowRightIcon, DumbbellIcon, FootprintsIcon, ShieldCheckIcon } from "lucide-react";
import { Brand } from "@/components/brand";
import { ThemeToggle } from "@/components/theme-toggle";
import { Button } from "@/components/ui/button";

const promises = [
  { icon: DumbbellIcon, title: "Your actual split", text: "Private templates you can change down to each set and rep." },
  { icon: FootprintsIcon, title: "Runs, honestly logged", text: "Distance and elapsed time stay manual and clear." },
  { icon: ShieldCheckIcon, title: "Your line, protected", text: "Every account sees only its own training data." },
];

export default function Home() {
  return <main className="grain min-h-dvh overflow-hidden"><header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Brand /><div className="flex items-center gap-2"><ThemeToggle /><Button size="lg" nativeButton={false} render={<Link href="/login" />}>Sign in <ArrowRightIcon data-icon="inline-end" /></Button></div></header><section className="mx-auto grid min-h-[76vh] max-w-7xl items-center gap-12 px-5 py-16 lg:grid-cols-[1.2fr_.8fr] lg:px-8"><div><p className="mb-8 text-xs font-bold uppercase tracking-[.24em] text-pulse">Manual training. Clear signal.</p><h1 className="display max-w-4xl text-6xl font-bold uppercase leading-[.86] sm:text-8xl lg:text-[7.6rem]">Hold the line.<br /><span className="text-pulse">Build proof.</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-muted-foreground sm:text-xl">A quiet record for the work you do: lifting, running, and the momentum that connects them.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Button size="lg" nativeButton={false} render={<Link href="/register" />}>Create your account <ArrowRightIcon data-icon="inline-end" /></Button><Button size="lg" variant="outline" nativeButton={false} render={<Link href="/login" />}>I already train here</Button></div></div><aside className="border border-pulse/25 bg-card/70 p-7 sm:p-9"><p className="display text-sm uppercase text-pulse">The principle</p><p className="display mt-7 text-4xl font-bold uppercase leading-none">Nothing invented.<br />Nothing hidden.</p><p className="mt-6 leading-7 text-muted-foreground">No sample score, no public leaderboard, no wearable assumptions. Sign in and your own line starts empty—ready for your first session.</p></aside></section><section className="mx-auto max-w-7xl border-t border-border px-5 py-16 lg:px-8"><div className="grid gap-px border border-border bg-border md:grid-cols-3">{promises.map(({ icon: Icon, title, text }, index) => <article key={title} className="bg-background p-7"><span className="display text-sm text-pulse">0{index + 1}</span><Icon className="my-8 size-8 text-pulse" /><h2 className="display text-2xl font-semibold uppercase">{title}</h2><p className="mt-3 leading-7 text-muted-foreground">{text}</p></article>)}</div></section><footer className="mx-auto flex max-w-7xl items-center justify-between px-5 py-10 text-sm text-muted-foreground lg:px-8"><Brand compact /><span>Built for the work nobody else sees.</span></footer></main>;
}
