import { Check, ChevronDown, ChevronUp, Dumbbell, Plus } from 'lucide-react-native';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Screen } from '@/components/screen';
import { AppButton, AppInput, AppText, Card, Pill, SectionHeading, divider } from '@/components/ui/primitives';
import { radius, spacing } from '@/constants/theme';
import { useActivities } from '@/contexts/activity-context';
import { useSweatlineTheme } from '@/contexts/theme-context';

type Entry = { name: string; weight: string; reps: string; sets: string; target: string };
const newEntry = (): Entry => ({ name: '', weight: '', reps: '10', sets: '3', target: 'Custom' });

export default function GymScreen() {
  const router = useRouter(); const { colors } = useSweatlineTheme(); const { activities, addWorkout, templates } = useActivities();
  const [mode, setMode] = useState<'log' | 'history'>('log'); const [selectedId, setSelectedId] = useState<string | null>(null); const [title, setTitle] = useState('');
  const [entries, setEntries] = useState<Entry[]>([]); const [open, setOpen] = useState<number | null>(0); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [page, setPage] = useState(0);
  const selected = templates.find((item) => item.id === selectedId);
  const loadTemplate = (id: string) => { const template = templates.find((item) => item.id === id); if (!template) return; setSelectedId(id); setTitle(template.name); setEntries(template.exercises.map((item) => ({ name: item.name, weight: '', reps: item.targetReps.match(/\d+/)?.[0] ?? '10', sets: String(item.targetSets), target: item.targetReps }))); setOpen(0); setSaved(false); };
  const update = (index: number, field: keyof Entry, value: string) => setEntries((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  const volume = useMemo(() => entries.reduce((sum, item) => sum + Number(item.weight || 0) * Number(item.reps || 0) * Number(item.sets || 0), 0), [entries]);
  const save = async () => { if (!entries.length || entries.some((item) => !item.name.trim())) return; setSaving(true); await addWorkout({ title: title.trim() || selected?.name || 'Workout', entries: entries.map((item) => ({ name: item.name.trim(), weight: Number(item.weight || 0), reps: Number(item.reps || 0), sets: Number(item.sets || 0) })) }); setSaving(false); setSaved(true); };
  const workouts = activities.filter((item) => item.kind === 'workout'); const perPage = 5; const shown = workouts.slice(page * perPage, page * perPage + perPage); const totalPages = Math.max(1, Math.ceil(workouts.length / perPage));
  return <Screen header={<View style={styles.header}><View><AppText variant="eyebrow" style={{ color: colors.pulse }}>Gym</AppText><AppText variant="display">Build the{'\n'}work.</AppText></View><View style={[styles.icon, { backgroundColor: colors.pulse }]}><Dumbbell size={26} color={colors.pulseText} /></View></View>}>
    <View style={[styles.mode, { backgroundColor: colors.elevated }]}><Pressable onPress={() => setMode('log')} style={[styles.modeButton, mode === 'log' && { backgroundColor: colors.pulse }]}><AppText variant="label" style={{ color: mode === 'log' ? colors.pulseText : colors.muted }}>Create activity</AppText></Pressable><Pressable onPress={() => setMode('history')} style={[styles.modeButton, mode === 'history' && { backgroundColor: colors.surface }]}><AppText variant="label" style={{ color: mode === 'history' ? colors.text : colors.muted }}>Your activities</AppText></Pressable></View>
    {mode === 'history' ? <><SectionHeading eyebrow={String(workouts.length) + ' sessions'} title="Gym history" /><Card style={styles.history}>{shown.length ? shown.map((workout, index) => <Pressable key={workout.id} onPress={() => (router.push as (path: string) => void)('/activity/' + workout.id)} style={[styles.historyRow, index < shown.length - 1 && divider(colors)]}><View style={[styles.number, { backgroundColor: colors.elevated }]}><Dumbbell size={19} color={colors.pulse} /></View><View style={{ flex: 1 }}><AppText variant="label">{workout.title}</AppText><AppText muted>{new Intl.DateTimeFormat('en', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(workout.occurredAt))} · {Array.isArray(workout.payload.exercises) ? workout.payload.exercises.length : 0} exercises</AppText></View><AppText variant="label">{Number(workout.payload.volumeKg ?? 0).toLocaleString()} kg</AppText></Pressable>) : <AppText muted>No gym sessions yet. Your first one will appear here.</AppText>}</Card>{workouts.length > perPage && <View style={styles.pager}><AppButton label="Previous" variant="ghost" disabled={page === 0} onPress={() => setPage((value) => value - 1)} /><AppText muted>Page {page + 1} of {totalPages}</AppText><AppButton label="Next" variant="ghost" disabled={page >= totalPages - 1} onPress={() => setPage((value) => value + 1)} /></View>}</> : <><SectionHeading eyebrow="Your split" title="Choose a template" action={<Pill tone="pulse">{templates.length} ready</Pill>} /><View style={styles.templateGrid}>{templates.map((template, index) => { const active = template.id === selected?.id; return <Pressable key={template.id} accessibilityRole="button" accessibilityState={{ selected: active }} onPress={() => loadTemplate(template.id)} style={[styles.template, { backgroundColor: active ? colors.pulse : colors.surface, borderColor: active ? colors.pulse : colors.border }]}><AppText variant="eyebrow" style={{ color: active ? colors.pulseText : colors.muted }}>{String(index + 1).padStart(2, '0')} · {template.category}</AppText><AppText variant="title" style={{ color: active ? colors.pulseText : colors.text, fontSize: 20 }}>{template.name}</AppText><AppText muted style={{ color: active ? colors.pulseText : colors.muted, fontSize: 13 }}>{template.exercises.length} exercises</AppText></Pressable>; })}</View>
      <SectionHeading eyebrow="Today" title={selected?.name ?? 'Your workout'} action={<Pill>{volume.toLocaleString()} kg</Pill>} /><Card style={styles.sessionCard}><AppInput value={title} onChangeText={setTitle} placeholder="Workout title" />{entries.map((entry, index) => <View key={String(index) + entry.name} style={[styles.exercise, index < entries.length - 1 && divider(colors)]}><Pressable onPress={() => setOpen((value) => value === index ? null : index)} style={styles.exerciseTitle}><View style={[styles.number, { backgroundColor: colors.elevated }]}><AppText variant="eyebrow" muted>{String(index + 1).padStart(2, '0')}</AppText></View><View style={{ flex: 1 }}><AppText variant="label">{entry.name || 'Untitled exercise'}</AppText><AppText muted>{entry.sets} sets · target {entry.target}</AppText></View>{open === index ? <ChevronUp size={19} color={colors.muted} /> : <ChevronDown size={19} color={colors.muted} />}</Pressable>{open === index && <View style={styles.fields}><View style={styles.fullField}><AppText variant="eyebrow" muted>Exercise</AppText><AppInput value={entry.name} onChangeText={(value) => update(index, 'name', value)} placeholder="Exercise name" /></View><View style={styles.field}><AppText variant="eyebrow" muted>Kg</AppText><AppInput value={entry.weight} onChangeText={(value) => update(index, 'weight', value)} keyboardType="decimal-pad" placeholder="0" /></View><View style={styles.field}><AppText variant="eyebrow" muted>Reps</AppText><AppInput value={entry.reps} onChangeText={(value) => update(index, 'reps', value)} keyboardType="number-pad" /></View><View style={styles.field}><AppText variant="eyebrow" muted>Sets</AppText><AppInput value={entry.sets} onChangeText={(value) => update(index, 'sets', value)} keyboardType="number-pad" /></View></View>}</View>)}</Card><AppButton label="Add an exercise" variant="secondary" icon={<Plus size={18} color={colors.text} />} onPress={() => { setEntries((items) => [...items, newEntry()]); setOpen(entries.length); }} full />{saved && <Card style={styles.success}><Check size={20} color={colors.pulse} /><AppText variant="label">Saved locally — use Sync when you are ready.</AppText></Card>}<AppButton label="Save gym session" icon={<Plus size={19} color={colors.pulseText} />} loading={saving} onPress={save} full /></>}
  </Screen>;
}

const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.xl }, icon: { width: 52, height: 52, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' }, mode: { padding: 4, borderRadius: radius.md, flexDirection: 'row', gap: 4 }, modeButton: { flex: 1, minHeight: 46, alignItems: 'center', justifyContent: 'center', borderRadius: 10 }, templateGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, template: { width: '48.7%', minHeight: 125, borderWidth: 1, borderRadius: radius.md, padding: 14, justifyContent: 'space-between' }, sessionCard: { gap: 0 }, exercise: { gap: 12, paddingVertical: 15 }, exerciseTitle: { flexDirection: 'row', alignItems: 'center', gap: 11 }, number: { width: 40, height: 40, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, fields: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, field: { flex: 1, minWidth: '29%', gap: 6 }, fullField: { width: '100%', gap: 6 }, success: { flexDirection: 'row', alignItems: 'center' }, history: { gap: 0, paddingVertical: 0 }, historyRow: { minHeight: 80, flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 13 }, pager: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' } });
