import { useRouter } from 'expo-router';
import { ArrowRight, Dumbbell, Footprints, RefreshCw, UserRound } from 'lucide-react-native';
import { useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { BrandMark } from '@/components/brand-mark';
import { SweatLevelBar } from '@/components/sweat-level-bar';
import { Screen } from '@/components/screen';
import { AppButton, AppText, Card, Pill, SectionHeading, divider } from '@/components/ui/primitives';
import { radius, spacing } from '@/constants/theme';
import { useActivities } from '@/contexts/activity-context';
import { useSweatlineTheme } from '@/contexts/theme-context';
import { formatPace } from '@/lib/fitness';

export default function HomeScreen() {
  const router = useRouter(); const { colors } = useSweatlineTheme(); const { account, activities, pendingCount, score, loading, syncNow, syncStatus } = useActivities();
  const [now] = useState(() => Date.now()); const week = activities.filter((item) => now - new Date(item.occurredAt).getTime() < 7 * 86400000);
  const gymCount = week.filter((item) => item.kind === 'workout').length; const runKm = week.filter((item) => item.kind === 'run').reduce((sum, item) => sum + Number(item.payload.distanceKm ?? 0), 0);
  const syncColor = !account ? colors.warm : pendingCount ? colors.warm : syncStatus === 'Error' ? colors.danger : colors.pulse;
  const header = <View style={styles.header}><View style={styles.brand}><View style={[styles.mark, { backgroundColor: colors.pulse }]}><BrandMark size={30} inverse /></View><View><AppText variant="title">Sweatline</AppText><AppText variant="eyebrow" muted>{new Intl.DateTimeFormat('en', { weekday: 'long', day: 'numeric', month: 'short' }).format(new Date(now))}</AppText></View></View><Pressable accessibilityRole="button" accessibilityLabel={account ? 'Sync your data' : 'Open account settings'} onPress={() => account ? void syncNow() : router.navigate('/settings')} style={[styles.syncButton, { borderColor: syncColor, backgroundColor: colors.surface }]}>{account ? <RefreshCw size={18} color={syncColor} /> : <UserRound size={18} color={syncColor} />}<View style={[styles.syncDot, { backgroundColor: syncColor }]} /></Pressable></View>;
  return <Screen header={header} refreshing={loading}>
    <View style={styles.stats}><Card style={styles.stat}><AppText variant="eyebrow" muted>Sessions</AppText><AppText variant="metric">{gymCount}</AppText><AppText muted>this week</AppText></Card><Card style={styles.stat}><AppText variant="eyebrow" muted>Distance</AppText><AppText variant="metric">{runKm.toFixed(1)}</AppText><AppText muted>kilometres</AppText></Card><Card style={styles.stat}><AppText variant="eyebrow" muted>Entries</AppText><AppText variant="metric">{week.length}</AppText><AppText muted>logged</AppText></Card></View>
    <Card style={styles.scoreCard}><View style={styles.scoreTop}><View><AppText variant="eyebrow" style={{ color: colors.pulse }}>Training rhythm</AppText><AppText variant="title">A clear view of your consistency.</AppText></View><Pill tone="pulse">7 / 28 days</Pill></View><View style={styles.scoreBody}><SweatLevelBar score={score} /><View style={styles.breakdown}>{[['Active days this week', score.consistency, 40], ['Weeks with movement', score.rhythm, 30], ['How recent your last session was', score.recency, 30]].map(([label, value, max]) => <View key={String(label)} style={styles.scoreRow}><View style={styles.scoreLabel}><View style={[styles.dot, { backgroundColor: colors.pulse }]} /><AppText variant="label">{label}</AppText></View><AppText variant="label" muted>{value}/{max}</AppText></View>)}</View></View><AppText muted style={styles.explainer}>This is a habit signal, not a recovery or injury-risk score. It never compares lifting volume with running distance.</AppText></Card>
    <View style={styles.actions}><AppButton label="Log workout" full icon={<Dumbbell size={19} color={colors.pulseText} />} onPress={() => router.navigate('/gym')} /><AppButton label="Log run" variant="secondary" full icon={<Footprints size={19} color={colors.text} />} onPress={() => router.navigate('/run')} /></View>
    <SectionHeading eyebrow="Latest" title="Recent line" /><Card style={styles.feed}>{activities.slice(0, 4).map((item, index) => <Pressable key={item.id} accessibilityRole="button" onPress={() => (router.push as (path: string) => void)('/activity/' + item.id)} style={[styles.feedRow, index < Math.min(activities.length, 4) - 1 && divider(colors)]}><View style={[styles.activityIcon, { backgroundColor: colors.elevated }]}>{item.kind === 'run' ? <Footprints size={20} color={colors.pulse} /> : <Dumbbell size={20} color={colors.pulse} />}</View><View style={styles.feedCopy}><AppText variant="label">{item.title}</AppText><AppText muted>{new Intl.DateTimeFormat('en', { weekday: 'short', month: 'short', day: 'numeric' }).format(new Date(item.occurredAt))}</AppText></View><View style={styles.feedValue}><AppText variant="label">{item.kind === 'run' ? Number(item.payload.distanceKm).toFixed(2) + ' km' : Number(item.payload.volumeKg).toLocaleString() + ' kg'}</AppText>{item.kind === 'run' && <AppText muted>{formatPace(Number(item.payload.distanceKm), Number(item.payload.durationSeconds))}</AppText>}</View><ArrowRight size={17} color={colors.muted} /></Pressable>)}</Card>
  </Screen>;
}

const styles = StyleSheet.create({ header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing.xl }, brand: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 }, mark: { width: 46, height: 46, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, syncButton: { width: 46, height: 46, borderWidth: 1, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', position: 'relative' }, syncDot: { width: 8, height: 8, borderRadius: 4, position: 'absolute', right: 7, top: 7 }, stats: { flexDirection: 'row', gap: 7 }, stat: { flex: 1, padding: 11, gap: 3 }, scoreCard: { padding: spacing.lg }, scoreTop: { gap: spacing.sm }, scoreBody: { alignItems: 'center', gap: spacing.lg }, breakdown: { width: '100%', gap: 13 }, scoreRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 }, scoreLabel: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 9 }, dot: { width: 8, height: 8 }, explainer: { fontSize: 13, lineHeight: 19 }, actions: { gap: spacing.sm }, feed: { gap: 0, paddingVertical: 0 }, feedRow: { minHeight: 78, flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 13 }, activityIcon: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, feedCopy: { flex: 1 }, feedValue: { alignItems: 'flex-end' } });
