import { Check, ExternalLink, Footprints } from 'lucide-react-native';
import { useMemo, useState } from 'react';
import { Linking, Pressable, StyleSheet, View } from 'react-native';
import { Screen } from '@/components/screen';
import { AppButton, AppInput, AppText, Card, Pill, SectionHeading, divider } from '@/components/ui/primitives';
import { radius, spacing } from '@/constants/theme';
import { useActivities } from '@/contexts/activity-context';
import { useSweatlineTheme } from '@/contexts/theme-context';
import { formatPace } from '@/lib/fitness';

const STRAVA = /^https?:\/\/(www\.)?strava\.com\/activities\/\d+/i;

export default function RunScreen() {
  const { colors } = useSweatlineTheme(); const { activities, addRun } = useActivities();
  const [title, setTitle] = useState(''); const [distance, setDistance] = useState(''); const [minutes, setMinutes] = useState(''); const [stravaUrl, setStravaUrl] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false);
  const pace = useMemo(() => formatPace(Number(distance), Number(minutes) * 60), [distance, minutes]);
  const save = async () => { const km = Number(distance); const seconds = Number(minutes) * 60; if (!km || !seconds) return setError('Enter a distance and elapsed time to save this run.'); if (stravaUrl && !STRAVA.test(stravaUrl)) return setError('Use a Strava activity URL such as strava.com/activities/123.'); setError(''); setSaving(true); await addRun({ title: title.trim() || 'Run', distanceKm: km, durationSeconds: seconds, stravaUrl: stravaUrl || undefined }); setSaving(false); setSaved(true); setTitle(''); setDistance(''); setMinutes(''); setStravaUrl(''); };
  const runs = activities.filter((item) => item.kind === 'run');
  return <Screen header={<View style={styles.header}><View><AppText variant="eyebrow" style={{ color: colors.pulse }}>Run log</AppText><AppText variant="display">Distance,{`\n`}on your terms.</AppText></View><View style={[styles.icon, { backgroundColor: colors.pulse }]}><Footprints size={26} color={colors.pulseText} /></View></View>}>
    <Card><SectionHeading eyebrow="Manual entry" title="Add a run" /><View style={styles.form}><View style={styles.twoCols}><View style={styles.field}><AppText variant="label">Distance · km</AppText><AppInput value={distance} onChangeText={setDistance} keyboardType="decimal-pad" placeholder="5.00" accessibilityLabel="Distance in kilometres" /></View><View style={styles.field}><AppText variant="label">Elapsed · min</AppText><AppInput value={minutes} onChangeText={setMinutes} keyboardType="decimal-pad" placeholder="28.5" accessibilityLabel="Elapsed time in minutes" /></View></View><View style={styles.field}><AppText variant="label">Run title</AppText><AppInput value={title} onChangeText={setTitle} placeholder="Easy evening 5K" /></View><View style={styles.field}><AppText variant="label">Strava activity link · optional</AppText><AppInput value={stravaUrl} onChangeText={setStravaUrl} autoCapitalize="none" keyboardType="url" placeholder="https://strava.com/activities/…" /><AppText muted style={styles.help}>Stored as a reference only. Enter distance and time manually.</AppText></View><View style={[styles.pace, { backgroundColor: colors.elevated }]}><AppText muted>Calculated pace</AppText><AppText variant="metric">{pace}</AppText></View>{error ? <AppText style={{ color: colors.danger }}>{error}</AppText> : null}{saved ? <View style={styles.saved}><Check size={18} color={colors.pulse} /><AppText variant="label" style={{ color: colors.pulse }}>Run saved locally</AppText></View> : null}<AppButton label="Save run" icon={<Footprints size={19} color={colors.pulseText} />} loading={saving} onPress={save} full /></View></Card>
    <SectionHeading eyebrow={`${runs.length} entries`} title="Run history" action={<Pill tone="pulse">{runs.reduce((sum, run) => sum + Number(run.payload.distanceKm ?? 0), 0).toFixed(1)} km</Pill>} />
    <Card style={styles.history}>{runs.map((run, index) => <View key={run.id} style={[styles.runRow, index < runs.length - 1 && divider(colors)]}><View style={[styles.runIcon, { backgroundColor: colors.elevated }]}><Footprints size={20} color={colors.pulse} /></View><View style={styles.runCopy}><AppText variant="label">{run.title}</AppText><AppText muted>{new Intl.DateTimeFormat('en', { day: 'numeric', month: 'short' }).format(new Date(run.occurredAt))} · {formatPace(Number(run.payload.distanceKm), Number(run.payload.durationSeconds))}</AppText></View><AppText variant="label">{Number(run.payload.distanceKm).toFixed(2)} km</AppText>{typeof run.payload.stravaUrl === 'string' && <Pressable accessibilityRole="link" accessibilityLabel={`Open ${run.title} in Strava`} hitSlop={12} onPress={() => Linking.openURL(run.payload.stravaUrl as string)}><ExternalLink size={18} color={colors.muted} /></Pressable>}</View>)}</Card>
  </Screen>;
}

const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.xl }, icon: { width: 52, height: 52, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' }, form: { gap: spacing.md }, twoCols: { flexDirection: 'row', gap: spacing.sm }, field: { flex: 1, gap: 7 }, help: { fontSize: 13, lineHeight: 18 }, pace: { borderRadius: radius.md, padding: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, saved: { flexDirection: 'row', alignItems: 'center', gap: 8 }, history: { gap: 0, paddingVertical: 0 }, runRow: { minHeight: 78, flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 14 }, runIcon: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, runCopy: { flex: 1 } });
