"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Field, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Profile = { username?: string | null; display_name?: string | null; theme_preference?: "light" | "dark" | "system"; distance_unit?: "km" | "mi"; weight_unit?: "kg" | "lb"; weekly_target?: number };
type Values = { username: string; display_name: string; theme_preference: "light" | "dark" | "system"; distance_unit: "km" | "mi"; weight_unit: "kg" | "lb"; weekly_target: number };
export function PreferencesForm({ profile }: { profile: Profile | null }) {
  const [values, setValues] = useState<Values>({ username: profile?.username ?? "", display_name: profile?.display_name ?? "", theme_preference: profile?.theme_preference ?? "system", distance_unit: profile?.distance_unit ?? "km", weight_unit: profile?.weight_unit ?? "kg", weekly_target: profile?.weekly_target ?? 4 }); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false);
  async function save() { const client = getSupabaseBrowserClient(); if (!client) return setMessage("Supabase is not configured."); setPending(true); const { data: { user } } = await client.auth.getUser(); const { error } = await client.from("sweatline_profiles").upsert({ ...values, user_id: user?.id, updated_at: new Date().toISOString() }); setPending(false); setMessage(error ? error.message : "Preferences saved."); }
  return <div className="grid gap-5"><div className="grid gap-5 sm:grid-cols-2"><Field><FieldLabel htmlFor="username">Username</FieldLabel><Input id="username" value={values.username} onChange={(event) => setValues({ ...values, username: event.target.value })} /></Field><Field><FieldLabel htmlFor="target">Weekly sessions target</FieldLabel><Input id="target" type="number" min="1" max="14" value={values.weekly_target} onChange={(event) => setValues({ ...values, weekly_target: Math.max(1, Math.min(14, Number(event.target.value) || 1)) })} /></Field></div><div className="grid grid-cols-3 gap-3"><label className="grid gap-2 text-sm font-medium">Theme<select value={values.theme_preference} onChange={(event) => setValues({ ...values, theme_preference: event.target.value as Values["theme_preference"] })} className="h-10 rounded-md border bg-background px-2"><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label className="grid gap-2 text-sm font-medium">Distance<select value={values.distance_unit} onChange={(event) => setValues({ ...values, distance_unit: event.target.value as Values["distance_unit"] })} className="h-10 rounded-md border bg-background px-2"><option value="km">km</option><option value="mi">mi</option></select></label><label className="grid gap-2 text-sm font-medium">Weight<select value={values.weight_unit} onChange={(event) => setValues({ ...values, weight_unit: event.target.value as Values["weight_unit"] })} className="h-10 rounded-md border bg-background px-2"><option value="kg">kg</option><option value="lb">lb</option></select></label></div>{message && <p role="status" className="text-sm text-muted-foreground">{message}</p>}<Button onClick={save} disabled={pending}>{pending ? "Saving…" : "Save preferences"}</Button></div>;
}
