"use client";

import { FormEvent, useMemo, useState } from "react";
import { ExternalLinkIcon, FootprintsIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { formatPace, type Run } from "@/lib/fitness";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

function seconds(value: string) { const parts = value.trim().split(":").map(Number); if (parts.some(Number.isNaN)) return 0; return parts.length === 3 ? parts[0] * 3600 + parts[1] * 60 + parts[2] : parts.length === 2 ? parts[0] * 60 + parts[1] : parts[0] * 60; }

export function RunManager({ initialRuns }: { initialRuns: Run[] }) {
  const [runs, setRuns] = useState(initialRuns); const [distance, setDistance] = useState(""); const [duration, setDuration] = useState(""); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false);
  const pace = useMemo(() => formatPace(Number(distance), seconds(duration)), [distance, duration]);
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const client = getSupabaseBrowserClient(); const durationSeconds = seconds(duration); const distanceKm = Number(distance);
    if (!client) return setMessage("Supabase is not configured."); if (!distanceKm || !durationSeconds) return setMessage("Enter a positive distance and elapsed time."); setPending(true);
    const { data: { user } } = await client.auth.getUser(); const result = await client.from("sweatline_runs").insert({ user_id: user?.id, title: String(form.get("title") || "Run").trim() || "Run", performed_at: new Date().toISOString(), distance_km: distanceKm, duration_seconds: durationSeconds, strava_url: String(form.get("strava") || "").trim() || null, notes: String(form.get("notes") || "").trim() || null, client_updated_at: new Date().toISOString() }).select().single(); setPending(false);
    if (result.error) return setMessage(result.error.message); setRuns((current) => [result.data as Run, ...current]); setDistance(""); setDuration(""); event.currentTarget.reset(); setMessage("Run saved.");
  }
  return <div className="grid gap-6 xl:grid-cols-[1fr_380px]"><Card><CardHeader><CardTitle className="display text-2xl uppercase">Add a run</CardTitle><CardDescription>Distance and elapsed time are required. Pace is calculated automatically.</CardDescription></CardHeader><CardContent><form onSubmit={save} className="flex flex-col gap-6"><FieldGroup><div className="grid gap-5 sm:grid-cols-2"><Field><FieldLabel htmlFor="distance">Distance (km)</FieldLabel><Input id="distance" value={distance} onChange={(event) => setDistance(event.target.value)} inputMode="decimal" placeholder="5.00" required /></Field><Field><FieldLabel htmlFor="duration">Elapsed time</FieldLabel><Input id="duration" value={duration} onChange={(event) => setDuration(event.target.value)} placeholder="28:30" required /><FieldDescription>mm:ss or hh:mm:ss</FieldDescription></Field></div><Field><FieldLabel htmlFor="title">Run title</FieldLabel><Input id="title" name="title" placeholder="Easy evening 5K" /></Field><Field><FieldLabel htmlFor="strava">Strava activity link</FieldLabel><Input id="strava" name="strava" type="url" placeholder="https://strava.com/activities/…" /></Field><Field><FieldLabel htmlFor="notes">Notes</FieldLabel><Input id="notes" name="notes" placeholder="Optional" /></Field></FieldGroup><div className="flex items-center justify-between rounded-lg bg-muted p-4"><span className="text-sm text-muted-foreground">Estimated pace</span><span className="display text-2xl font-bold tabular-nums">{pace}</span></div>{message && <p role="status" className="text-sm text-muted-foreground">{message}</p>}<Button type="submit" disabled={pending}>{pending ? "Saving…" : "Save run"} <FootprintsIcon data-icon="inline-end" /></Button></form></CardContent></Card><Card><CardHeader><CardTitle className="display text-2xl uppercase">Run history</CardTitle><CardDescription>{runs.length ? `${runs.reduce((sum, item) => sum + Number(item.distance_km), 0).toFixed(1)} km logged` : "Your first run will appear here."}</CardDescription></CardHeader><CardContent className="flex flex-col gap-5">{runs.length ? runs.map((run) => <div key={run.id} className="flex items-center gap-3 border-b pb-5 last:border-0"><span className="grid size-10 place-items-center rounded-lg bg-muted"><FootprintsIcon className="size-5" /></span><div className="min-w-0 flex-1"><p className="font-semibold">{run.title || "Run"}</p><p className="text-sm text-muted-foreground">{new Intl.DateTimeFormat("en", { month: "short", day: "numeric" }).format(new Date(run.performed_at))} · {Number(run.distance_km).toFixed(2)} km · {formatPace(Number(run.distance_km), run.duration_seconds)}</p></div>{run.strava_url && <Button variant="ghost" size="icon" nativeButton={false} render={<a href={run.strava_url} target="_blank" rel="noreferrer" aria-label="Open in Strava" />}><ExternalLinkIcon /></Button>}</div>) : <p className="text-sm text-muted-foreground">No runs yet. Log the route you actually ran.</p>}</CardContent></Card></div>;
}
